@BlazorWebAPIAuthentication_HostAddress = https://localhost:7162

GET {{BlazorWebAPIAuthentication_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BlazorWebAPIAuthentication_HostAddress}}/api/user
Authorization: Bearer CfDJ8BjaLtYD_oFHugmyLPfEayzr--hZbnzaWtRhzdIq_Ar8pI9Nw3il7ylo0YABd5ejWDTv9maROlBhexT-4FJ8C4w9zbudfvc5x_lWgqg8vqSQ3Z1aeny4CEPgbsmwdcX-8TlK_0VuzjtlUl6tSg6XfpzSfwEzcr1ET4RGgySsv0UNw_DIatnagitNWgSpse78ecmkP4lrQElxt5KD0ofLkMHWCdJKai9J2FOkL7lOOBX-IVhT5LPyflToY9Lumwx5h2qb0C7LTYOCdRTwtalGqd0QE55ERmYTvuIZeG6ushC8uawOgqkQbkPNGbuEM6wpDVAxi1IZAauXt-C2Q4_PXT8R4ODW6Q34qbLVbczDgihTUK65LUr1-xRDWmx8_kkt4dspw09LZx9BbMaKVRbdp-tZIML5YoPUD-GFeoMzMwLgEStO61sUWKKmacP_uJXZtXgQl_I8jQvedMRLGir5CWo0qc2ik0vNp7BfLa8qLs53OtwaCq6UaO7ZKoB5OQmNlA2dm2VgcVeQukNKzV-LTNFD3PVXA8aRyfAJbBk-FbkDhvLX4SBJhDeikdBnYpwoRmgnX027gW6wqrgq0ayHalI4V4Rjig6n-6ZOOhyKU3iSOkXRnXC1VV683phKwSv6el_0oSoraAxcoEBasSCrIhGSYWGi3nSOg_NVi8I9AprxLPizEFkb-Sw0rdobYDnVyg
###

